In [30]:
import pandas as pd 
import numpy as np 
import seaborn as sns

In [31]:
#built in datasets available in seaborne
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [32]:
df=sns.load_dataset('iris')
df.shape

(150, 5)

In [33]:
df.columns.tolist()

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [34]:
df.sample(6)

     sepal_length  sepal_width  petal_length  petal_width    species
28            5.2          3.4           1.4          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
116           6.5          3.0           5.5          1.8  virginica
141           6.9          3.1           5.1          2.3  virginica
133           6.3          2.8           5.1          1.5  virginica
27            5.2          3.5           1.5          0.2     setosa

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [36]:
#generates a descriptive statistics that summarize
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [37]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [38]:
#removing setosa samples from the dataset, since logistic regr. gives binary classification
df=df[df['species']!='setosa']

In [39]:
df.shape

(100, 5)

In [40]:
#convert the categorical features into numerical features 
df['species']=df['species'].map({'versicolor':0,'virginica':1})

In [41]:
#df['species']=df['species'].replace({'versicolor':0,'virginica':1})

In [42]:
df.head()

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

In [43]:
df.tail(7)

     sepal_length  sepal_width  petal_length  petal_width  species
143           6.8          3.2           5.9          2.3        1
144           6.7          3.3           5.7          2.5        1
145           6.7          3.0           5.2          2.3        1
146           6.3          2.5           5.0          1.9        1
147           6.5          3.0           5.2          2.0        1
148           6.2          3.4           5.4          2.3        1
149           5.9          3.0           5.1          1.8        1

In [46]:
df['species'].unique()

array([0, 1])

In [47]:
df

     sepal_length  sepal_width  petal_length  petal_width  species
50            7.0          3.2           4.7          1.4        0
51            6.4          3.2           4.5          1.5        0
52            6.9          3.1           4.9          1.5        0
53            5.5          2.3           4.0          1.3        0
54            6.5          2.8           4.6          1.5        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        1
146           6.3          2.5           5.0          1.9        1
147           6.5          3.0           5.2          2.0        1
148           6.2          3.4           5.4          2.3        1
149           5.9          3.0           5.1          1.8        1

[100 rows x 5 columns]

In [53]:
X=df.iloc[:,:-1] #IV-Independent Variables, all rows, columns except the last columns
y=df.iloc[:,-1] #DV-Dependent Variables, all rows and only the last column

In [55]:
X.shape, y.shape # y.shape cant be (100,1) because it becomes a vector i.e 1D

((100, 4), (100,))

In [56]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [58]:
X_train.shape, y_train.shape

((75, 4), (75,))

In [59]:
X_test.shape, y_test.shape

((25, 4), (25,))

In [60]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [61]:
y_pred=classifier.predict(X_test)

In [64]:
from sklearn.metrics import(
confusion_matrix,
accuracy_score,
classification_report,
recall_score,
f1_score,
log_loss)

In [65]:
acc=accuracy_score(y_test,y_pred)
acc

0.92

In [68]:
f1=f1_score(y_test,y_pred)
f1

0.9090909090909091

In [70]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[13,  1],
       [ 1, 10]])

In [71]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        14
           1       0.91      0.91      0.91        11

    accuracy                           0.92        25
   macro avg       0.92      0.92      0.92        25
weighted avg       0.92      0.92      0.92        25